# Use postgres/example user/password credentials
version: '3.9'

services:

  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: solver
      POSTGRES_PASSWORD: root
      POSTGRES_DB: liberprimus
    volumes:
      #- type: volume
      #  source: db_data
      #  target: /var/lib/postgresql/data
      - type: bind
        source: ./db/sql/
        target: /docker-entrypoint-initdb.d/
        read_only: true

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
